"""
PDF report builder using ReportLab.

Provides both a general PDFReport class for building custom reports
and a `generate_quality_pdf()` convenience function for the standard
data-quality report.
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image,
)
from datetime import datetime
from pathlib import Path
import logging

from config import APP_TITLE, APP_VERSION

log = logging.getLogger(__name__)


class PDFReport:
    """Fluent builder for multi-section PDF reports."""

    def __init__(self, path: str):
        self._path = Path(path)
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._doc = SimpleDocTemplate(str(self._path), pagesize=letter,
                                      leftMargin=72, rightMargin=72,
                                      topMargin=72, bottomMargin=36)
        self._styles = getSampleStyleSheet()
        self._story = []

        # Custom styles
        self._styles.add(ParagraphStyle(
            "DocTitle", parent=self._styles["Heading1"],
            fontSize=22, textColor=colors.HexColor("#2C3E50"),
            spaceAfter=24, alignment=TA_CENTER,
        ))
        self._styles.add(ParagraphStyle(
            "Section", parent=self._styles["Heading2"],
            fontSize=15, textColor=colors.HexColor("#34495E"),
            spaceBefore=14, spaceAfter=8,
        ))

    def title(self, text: str):
        self._story.append(Paragraph(text, self._styles["DocTitle"]))
        return self

    def section(self, text: str):
        self._story.append(Paragraph(text, self._styles["Section"]))
        return self

    def text(self, html: str):
        self._story.append(Paragraph(html, self._styles["Normal"]))
        self._story.append(Spacer(1, 6))
        return self

    def kv_table(self, data: dict):
        """Key-value metadata table."""
        rows = [[k, str(v)] for k, v in data.items()]
        t = Table(rows, colWidths=[2 * inch, 4 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#34495E")),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
            ("BACKGROUND", (1, 0), (1, -1), colors.HexColor("#ECF0F1")),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        self._story.append(t)
        self._story.append(Spacer(1, 12))
        return self

    def data_table(self, rows: list, headers: list, col_widths=None):
        all_rows = [headers] + rows
        t = Table(all_rows, colWidths=col_widths)
        style = [
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#34495E")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]
        t.setStyle(TableStyle(style))
        self._story.append(t)
        self._story.append(Spacer(1, 12))
        return self

    def image(self, path: str, width=6 * inch):
        if Path(path).exists():
            self._story.append(Image(path, width=width, height=width * 0.6))
            self._story.append(Spacer(1, 8))
        return self

    def score_badge(self, score: float):
        """Visual quality score with color-coded rating."""
        if score >= 90:
            color, label = "#27ae60", "Excellent"
        elif score >= 75:
            color, label = "#2980b9", "Good"
        elif score >= 60:
            color, label = "#f39c12", "Fair"
        else:
            color, label = "#e74c3c", "Poor"

        style = ParagraphStyle("Score", parent=self._styles["Normal"],
                               fontSize=14, textColor=colors.HexColor(color),
                               alignment=TA_CENTER)
        self._story.append(Paragraph(f"<b>Quality Score: {score:.1f}/100</b>", style))
        self._story.append(Paragraph(f"<i>Rating: {label}</i>", self._styles["Normal"]))
        self._story.append(Spacer(1, 12))
        return self

    def save(self) -> str:
        footer = f"Generated by {APP_TITLE} v{APP_VERSION} — {datetime.now():%Y-%m-%d %H:%M}"
        self._story.append(Spacer(1, 24))
        self._story.append(Paragraph(footer, self._styles["Normal"]))
        self._doc.build(self._story)
        log.info("PDF saved: %s", self._path)
        return str(self._path)


# ---------------------------------------------------------------------------
# Convenience function for the standard quality report
# ---------------------------------------------------------------------------

def generate_quality_pdf(dataset_name: str, quality: dict,
                         output_path: str, charts: dict = None) -> str:
    pdf = PDFReport(output_path)
    pdf.title("Data Quality Report")
    pdf.kv_table({
        "Dataset": dataset_name,
        "Generated": f"{datetime.now():%Y-%m-%d %H:%M}",
        "Rows": quality.get("total_rows", "?"),
        "Columns": quality.get("total_columns", "?"),
    })

    if "overall_quality_score" in quality:
        pdf.section("Quality Assessment")
        pdf.score_badge(quality["overall_quality_score"])

    if "completeness" in quality:
        pdf.section("Completeness")
        if charts and "completeness" in charts:
            pdf.image(charts["completeness"])
        rows = [
            [field, str(d["null_count"]), f"{d['completeness_pct']:.1f}%"]
            for field, d in quality["completeness"].items()
        ]
        pdf.data_table(rows, ["Field", "Nulls", "Complete"],
                       [2.5 * inch, 1.5 * inch, 1.5 * inch])

    if quality.get("duplicates"):
        pdf.section("Duplicates")
        pdf.text(f"Found <b>{quality['duplicates']}</b> duplicate rows.")

    anomalies = quality.get("anomalies", {})
    if anomalies.get("anomalies_found", 0) > 0:
        pdf.section("Anomaly Detection")
        pdf.text(
            f"Detected <b>{anomalies['anomalies_found']}</b> anomalies "
            f"out of {anomalies['total_rows']} rows."
        )
        if charts and "anomalies" in charts:
            pdf.image(charts["anomalies"])

    return pdf.save()
